version: '3'
services: 
  nginx:
    image: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./certs:/etc/ssl/private
    links:
    - 001lfimagichashes
    - 002shoppingcartwww
    - 003fileupload
    - 004emoji
    - 005fileuploadcomments
    - 006hashcollision
    - 007roulette
    - 008ssrf
    - 009xxe
    - 010base64
    - 011serealize
    - 012selectsqlwww
    - 013captcha
    - 014hackinggame
    - 015googleauthdns
    - 015googleauthwww
    - 016nginx
    - 017domxss
    - 018resetpass
    - 019insta
    - 020accesslog
    - 021guessthenumber
    - 022bloglfi
    - 023vb
    - 024apk
    - 025easysql


  001lfimagichashes:
    build: ./001lfihashes/.
    expose:
    - "80"
  002shoppingcartwww:
    build: ./002shoppingcart/.
    expose:
    - "80"
    links:
        - 002shoppingcartdb
  002shoppingcartdb:
    image: mysql:8.0
    expose:
        - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: not_brutforsable_user
        MYSQL_PASSWORD: not_brutforsable_password
        MYSQL_ROOT_PASSWORD: not_brutforsable_password
    volumes:
        - ./002shoppingcart/dump:/docker-entrypoint-initdb.d
        - ./002shoppingcart/conf:/etc/mysql/conf.d
  003fileupload:
    build: ./003fileupload/.
    expose:
    - "80"
  004emoji:
    build: ./004emoji/.
    expose:
    - "80"
  005fileuploadcomments:
    build: ./005fileuploadtmp/.
    expose:
    - "80"
  006hashcollision:
    build: ./006hashcollision/.
    expose:
    - "80"
  007roulette:
    build: ./007roulette/.
    expose:
    - "80"
  008ssrf:
    build: ./008ssrf/.
    expose:
    - "80"
  009xxe:
    build: ./009xxe/.
    expose:
    - "8080"
  010base64:
    build: ./010base64/.
    expose:
    - "80"
  011serealize:
    build: ./011serealize/.
    expose:
    - "80"
  012selectsqlwww:
    build: ./012selectsql/.
    expose:
    - "80"
    links:
            - 012selectsqldb
  012selectsqldb:
    image: mysql:8.0
    expose:
        - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: not_brutforsable_user
        MYSQL_PASSWORD: not_brutforsable_password
        MYSQL_ROOT_PASSWORD: not_brutforsable_password
    volumes:
        - ./012selectsql/dump:/docker-entrypoint-initdb.d
        - ./012selectsql/conf:/etc/mysql/conf.d
  013captcha:
    build: ./013captcha/.
    expose:
    - "80"
  014hackinggame:
    build: ./014hackinggame/.
    expose:
    - "80"
  015googleauthdns:
   image: vulhub/bind:latest
   expose:
    - "53/tcp"
    - "53/udp"
   volumes:
    - ./015googleauth/named.conf.local:/etc/bind/named.conf.local
    - ./015googleauth/vulhub.db:/etc/bind/vulhub.db
  015googleauthwww:
    build: ./015googleauth/.
    expose:
        - "80"
  016nginx:
    build: ./016nginx/.
    expose:
    - "80"
  017domxss:
    build: ./017domxss/.
    expose:
    - "80"
  018resetpass:
    build: ./018resetpass/.
    expose:
    - "80"
  019insta:
    build: ./019insta/.
    expose:
    - "80"
  020accesslog:
    build: ./020accesslog/.
    expose:
    - "80"
  021guessthenumber:
    build: ./021guessthenumber/.
    expose:
    - "80"
  022bloglfi:
    build: ./022bloglfi/.
    expose:
    - "80"
  023vb:
    build: ./023vb/.
    expose:
    - "80"
  024apk:
    build: ./024apk/.
    expose:
    - "80"
  025easysql:
    build: ./025easysql/.
    expose:
    - "80"