version: "3.1"
services:
  002shoppingcartwww:
    build: ./.
    ports:
    - "80:80"
    links:
        - 002shoppingcartdb
  002shoppingcartdb:
    image: mysql:8.0
    expose:
        - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: not_brutforsable_user
        MYSQL_PASSWORD: not_brutforsable_password
        MYSQL_ROOT_PASSWORD: not_brutforsable_password
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
