--
-- Table structure for table `logos`
--

DROP TABLE IF EXISTS `logos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `logos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `used` tinyint(1) DEFAULT 0,
  `enabled` tinyint(1) DEFAULT 1,
  `protected` tinyint(1) DEFAULT 0,
  `custom` tinyint(1) DEFAULT 0,
  `name` text DEFAULT NULL,
  `logo` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `logos`
--

LOCK TABLES `logos` WRITE;
/*!40000 ALTER TABLE `logos` DISABLE KEYS */;
INSERT INTO `logos` (name, logo, protected, used, custom) VALUES ('admin', '/static/svg/icons/badges/badge-admin.svg', 1, 1, 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('4chan-2', '/static/svg/icons/badges/badge-4chan-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('4chan', '/static/svg/icons/badges/badge-4chan.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('8ball', '/static/svg/icons/badges/badge-8ball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('alien-2', '/static/svg/icons/badges/badge-alien-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('alien-3', '/static/svg/icons/badges/badge-alien-3.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('alien', '/static/svg/icons/badges/badge-alien.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('anchor', '/static/svg/icons/badges/badge-anchor.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('apple', '/static/svg/icons/badges/badge-apple.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('atom', '/static/svg/icons/badges/badge-atom.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('ax', '/static/svg/icons/badges/badge-ax.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('b', '/static/svg/icons/badges/badge-b.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bar-graph', '/static/svg/icons/badges/badge-bar-graph.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('barking', '/static/svg/icons/badges/badge-barking.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('baseball', '/static/svg/icons/badges/badge-baseball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('basketball-hoop', '/static/svg/icons/badges/badge-basketball-hoop.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('basketball', '/static/svg/icons/badges/badge-basketball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bat', '/static/svg/icons/badges/badge-bat.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('batman', '/static/svg/icons/badges/badge-batman.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('battery', '/static/svg/icons/badges/badge-battery.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('beaker', '/static/svg/icons/badges/badge-beaker.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bike', '/static/svg/icons/badges/badge-bike.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bluetooth', '/static/svg/icons/badges/badge-bluetooth.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('boba-fett', '/static/svg/icons/badges/badge-boba-fett.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bomb', '/static/svg/icons/badges/badge-bomb.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bone', '/static/svg/icons/badges/badge-bone.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('boomerang', '/static/svg/icons/badges/badge-boomerang.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bow-arrow', '/static/svg/icons/badges/badge-bow-arrow.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bowling-ball', '/static/svg/icons/badges/badge-bowling-ball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bowling-pin', '/static/svg/icons/badges/badge-bowling-pin.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('bowtie', '/static/svg/icons/badges/badge-bowtie.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('box', '/static/svg/icons/badges/badge-box.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('boxing-glove', '/static/svg/icons/badges/badge-boxing-glove.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('broomstick', '/static/svg/icons/badges/badge-broomstick.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('burger', '/static/svg/icons/badges/badge-burger.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('c3po', '/static/svg/icons/badges/badge-c3po.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cactus', '/static/svg/icons/badges/badge-cactus.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('california', '/static/svg/icons/badges/badge-california.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('camera', '/static/svg/icons/badges/badge-camera.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('captain-america', '/static/svg/icons/badges/badge-captain-america.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('car', '/static/svg/icons/badges/badge-car.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cat', '/static/svg/icons/badges/badge-cat.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('centaur', '/static/svg/icons/badges/badge-centaur.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('checkmark', '/static/svg/icons/badges/badge-checkmark.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cherry', '/static/svg/icons/badges/badge-cherry.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('chess-knight', '/static/svg/icons/badges/badge-chess-knight.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('chess-rook', '/static/svg/icons/badges/badge-chess-rook.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('chevron-corporal', '/static/svg/icons/badges/badge-chevron-corporal.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('chevron-flag', '/static/svg/icons/badges/badge-chevron-flag.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cloud', '/static/svg/icons/badges/badge-cloud.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('coffee', '/static/svg/icons/badges/badge-coffee.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('command', '/static/svg/icons/badges/badge-command.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('compass', '/static/svg/icons/badges/badge-compass.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('computer-mouse', '/static/svg/icons/badges/badge-computer-mouse.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cone', '/static/svg/icons/badges/badge-cone.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('corndog', '/static/svg/icons/badges/badge-corndog.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('crown', '/static/svg/icons/badges/badge-crown.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cupcake', '/static/svg/icons/badges/badge-cupcake.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('cursor', '/static/svg/icons/badges/badge-cursor.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('darth-vader', '/static/svg/icons/badges/badge-darth-vader.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('deadpool', '/static/svg/icons/badges/badge-deadpool.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('deal-with-it', '/static/svg/icons/badges/badge-deal-with-it.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('deathly-hollows', '/static/svg/icons/badges/badge-deathly-hollows.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('diamond', '/static/svg/icons/badges/badge-diamond.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('dirtbike', '/static/svg/icons/badges/badge-dirtbike.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('dog', '/static/svg/icons/badges/badge-dog.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('double-ax', '/static/svg/icons/badges/badge-double-ax.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('drop', '/static/svg/icons/badges/badge-drop.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('dumbell', '/static/svg/icons/badges/badge-dumbell.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('egg', '/static/svg/icons/badges/badge-egg.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('elephant', '/static/svg/icons/badges/badge-elephant.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('eye', '/static/svg/icons/badges/badge-eye.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-cloud', '/static/svg/icons/badges/badge-face-cloud.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-helmeted', '/static/svg/icons/badges/badge-face-helmeted.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-sad', '/static/svg/icons/badges/badge-face-sad.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-star', '/static/svg/icons/badges/badge-face-star.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-toast', '/static/svg/icons/badges/badge-face-toast.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('face-tongue', '/static/svg/icons/badges/badge-face-tongue.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('feather', '/static/svg/icons/badges/badge-feather.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('flag', '/static/svg/icons/badges/badge-flag.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('flower-2', '/static/svg/icons/badges/badge-flower-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('flower', '/static/svg/icons/badges/badge-flower.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('football', '/static/svg/icons/badges/badge-football.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('fork', '/static/svg/icons/badges/badge-fork.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('fries', '/static/svg/icons/badges/badge-fries.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('game-controller', '/static/svg/icons/badges/badge-game-controller.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('glasses', '/static/svg/icons/badges/badge-glasses.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('green-lantern', '/static/svg/icons/badges/badge-green-lantern.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('guy-fawkes', '/static/svg/icons/badges/badge-guy-fawkes.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('hat-viking', '/static/svg/icons/badges/badge-hat-viking.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('hat-witch', '/static/svg/icons/badges/badge-hat-witch.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('head-lego', '/static/svg/icons/badges/badge-head-lego.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('headphones', '/static/svg/icons/badges/badge-headphones.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('heart', '/static/svg/icons/badges/badge-heart.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('high-heel', '/static/svg/icons/badges/badge-high-heel.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('home', '/static/svg/icons/badges/badge-home.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('hook', '/static/svg/icons/badges/badge-hook.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('hotdog', '/static/svg/icons/badges/badge-hotdog.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('html-file-2', '/static/svg/icons/badges/badge-html-file-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('html-file', '/static/svg/icons/badges/badge-html-file.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('html', '/static/svg/icons/badges/badge-html.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('ice-cream', '/static/svg/icons/badges/badge-ice-cream.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('infinity', '/static/svg/icons/badges/badge-infinity.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('invader-2', '/static/svg/icons/badges/badge-invader-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('invader', '/static/svg/icons/badges/badge-invader.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('iron-man', '/static/svg/icons/badges/badge-iron-man.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('jack-o-lantern', '/static/svg/icons/badges/badge-jack-o-lantern.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('jeep', '/static/svg/icons/badges/badge-jeep.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('kangaroo', '/static/svg/icons/badges/badge-kangaroo.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('kanye-glasses', '/static/svg/icons/badges/badge-kanye-glasses.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('key', '/static/svg/icons/badges/badge-key.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('kite', '/static/svg/icons/badges/badge-kite.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('knife', '/static/svg/icons/badges/badge-knife.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('lightbulb', '/static/svg/icons/badges/badge-lightbulb.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('lightning', '/static/svg/icons/badges/badge-lightning.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('location', '/static/svg/icons/badges/badge-location.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('man-newspaper', '/static/svg/icons/badges/badge-man-newspaper.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('marker', '/static/svg/icons/badges/badge-marker.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('monkey', '/static/svg/icons/badges/badge-monkey.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('monopoly-man', '/static/svg/icons/badges/badge-monopoly-man.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('moon', '/static/svg/icons/badges/badge-moon.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('moustache', '/static/svg/icons/badges/badge-moustache.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('music', '/static/svg/icons/badges/badge-music.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('mystery-man', '/static/svg/icons/badges/badge-mystery-man.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('nascar', '/static/svg/icons/badges/badge-nascar.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pacman-ghost', '/static/svg/icons/badges/badge-pacman-ghost.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pacman', '/static/svg/icons/badges/badge-pacman.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('paperclip', '/static/svg/icons/badges/badge-paperclip.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('peace-sign', '/static/svg/icons/badges/badge-peace-sign.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('peace', '/static/svg/icons/badges/badge-peace.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pencil-sharpener', '/static/svg/icons/badges/badge-pencil-sharpener.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('penguin', '/static/svg/icons/badges/badge-penguin.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('penrose-triangle', '/static/svg/icons/badges/badge-penrose-triangle.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pi', '/static/svg/icons/badges/badge-pi.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('picasa', '/static/svg/icons/badges/badge-picasa.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('plane', '/static/svg/icons/badges/badge-plane.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('plasma-gun', '/static/svg/icons/badges/badge-plasma-gun.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('plug', '/static/svg/icons/badges/badge-plug.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pokemon', '/static/svg/icons/badges/badge-pokemon.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('puma', '/static/svg/icons/badges/badge-puma.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('pyramid', '/static/svg/icons/badges/badge-pyramid.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('r2d2', '/static/svg/icons/badges/badge-r2d2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('radiation', '/static/svg/icons/badges/badge-radiation.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('rainbow', '/static/svg/icons/badges/badge-rainbow.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('reset', '/static/svg/icons/badges/badge-reset.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('revolver', '/static/svg/icons/badges/badge-revolver.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('robber', '/static/svg/icons/badges/badge-robber.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('robot', '/static/svg/icons/badges/badge-robot.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('rocker', '/static/svg/icons/badges/badge-rocker.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('rocket', '/static/svg/icons/badges/badge-rocket.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('rollerblade', '/static/svg/icons/badges/badge-rollerblade.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('sailboat', '/static/svg/icons/badges/badge-sailboat.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('saturn', '/static/svg/icons/badges/badge-saturn.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('sauron', '/static/svg/icons/badges/badge-sauron.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('sharethis', '/static/svg/icons/badges/badge-sharethis.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('shark', '/static/svg/icons/badges/badge-shark.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('shirt', '/static/svg/icons/badges/badge-shirt.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('shoe', '/static/svg/icons/badges/badge-shoe.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('skateboard', '/static/svg/icons/badges/badge-skateboard.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('skateboarder', '/static/svg/icons/badges/badge-skateboarder.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('skiier', '/static/svg/icons/badges/badge-skiier.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('skull-crossbones', '/static/svg/icons/badges/badge-skull-crossbones.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('snowboarder', '/static/svg/icons/badges/badge-snowboarder.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('soccerball', '/static/svg/icons/badges/badge-soccerball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('sock', '/static/svg/icons/badges/badge-sock.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('spaceship-2', '/static/svg/icons/badges/badge-spaceship-2.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('spaceship', '/static/svg/icons/badges/badge-spaceship.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('speech-bubble', '/static/svg/icons/badges/badge-speech-bubble.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('speeding-ball', '/static/svg/icons/badges/badge-speeding-ball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('spiderweb', '/static/svg/icons/badges/badge-spiderweb.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('stars', '/static/svg/icons/badges/badge-stars.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('stereo', '/static/svg/icons/badges/badge-stereo.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('stormtrooper', '/static/svg/icons/badges/badge-stormtrooper.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('swimmer', '/static/svg/icons/badges/badge-swimmer.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('swords', '/static/svg/icons/badges/badge-swords.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tank', '/static/svg/icons/badges/badge-tank.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tennis', '/static/svg/icons/badges/badge-tennis.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tetris-j', '/static/svg/icons/badges/badge-tetris-j.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tetris-t', '/static/svg/icons/badges/badge-tetris-t.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tetris-z', '/static/svg/icons/badges/badge-tetris-z.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('thors-hammer', '/static/svg/icons/badges/badge-thors-hammer.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('throwing-star', '/static/svg/icons/badges/badge-throwing-star.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('thumbsup', '/static/svg/icons/badges/badge-thumbsup.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tooth', '/static/svg/icons/badges/badge-tooth.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('tophat', '/static/svg/icons/badges/badge-tophat.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('traffic-cone', '/static/svg/icons/badges/badge-traffic-cone.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('trophy', '/static/svg/icons/badges/badge-trophy.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('turkey-leg', '/static/svg/icons/badges/badge-turkey-leg.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('umbrella', '/static/svg/icons/badges/badge-umbrella.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('unicorn', '/static/svg/icons/badges/badge-unicorn.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('unicycle', '/static/svg/icons/badges/badge-unicycle.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('vampire', '/static/svg/icons/badges/badge-vampire.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('venn-diagram', '/static/svg/icons/badges/badge-venn-diagram.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('volleyball', '/static/svg/icons/badges/badge-volleyball.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('vulcan-salute', '/static/svg/icons/badges/badge-vulcan-salute.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('watch', '/static/svg/icons/badges/badge-watch.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('watergun', '/static/svg/icons/badges/badge-watergun.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('whale', '/static/svg/icons/badges/badge-whale.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('whistle', '/static/svg/icons/badges/badge-whistle.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('wifi', '/static/svg/icons/badges/badge-wifi.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('x-and-o', '/static/svg/icons/badges/badge-x-and-o.svg', 0);
INSERT INTO `logos` (name, logo, custom) VALUES ('x-men', '/static/svg/icons/badges/badge-x-men.svg', 0);
/*!40000 ALTER TABLE `logos` ENABLE KEYS */;
UNLOCK TABLES;
