version: "3.1"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./src/:/var/www/html/
        links:
            - 012selectsqldb
        networks:
            - default
    012selectsqldb:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: not_brutforsable_user
            MYSQL_PASSWORD: not_brutforsable_password
            MYSQL_ROOT_PASSWORD: not_brutforsable_password
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
